apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-router-28
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-router-28
    app.kubernetes.io/part-of: kserve-router
  name: kserve-router-28
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-router-28
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-router-28
    spec:
      containers:
      - image: quay.io/modh/kserve-router@sha256:556b71b3346d2fa055cdcc593c5365e21a4c2dae534e143385c66705c466406f
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
