apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-router
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-router
    app.kubernetes.io/part-of: kserve-router
  name: kserve-router
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-router
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-router
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-router/kserve-router@sha256:de9ebbf774e740b11a814cfb689dfa20fe61ea50b3ced3de0aec54487c54ecc8
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
