apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-router-28
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/modh/kserve-router@sha256:1e8c96f5a094430b3a5f722b235574f533ad3c38c3ab6e7be6118ea87bd54797
        name: container-image
        resources: {}
status: {}
