apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-router-28
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/modh/kserve-router@sha256:21d74d55a8825495acd322dc88b230cfb5c93938c393defcc7867a50b28995f3
        name: container-image
        resources: {}
status: {}
