apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-router
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-router/kserve-router@sha256:472676777e277681ef226bdec0ab400c1d6489f9f414df4b57f58cdc74def025
        name: container-image
        resources: {}
status: {}
