apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-router
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-router/kserve-router@sha256:26f8b1881dbb1cfe1c108345f15509c954f586e5fea36550d174aaf69951d3bd
        name: container-image
        resources: {}
status: {}
